version: '3.1'
services:
  db:
    restart: always
    image: mysql:5.7.22
    container_name: mysql
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_ROOT_HOST: '%'
      MYSQL_USER: root
    command:
      --default-authentication-plugin=mysql_native_password
    volumes:
      - /usr/local/docker/secondcloud/mysql/conf:/etc/mysql
      - /usr/local/docker/secondcloud/mysql/logs:/var/log/mysql
      - /usr/local/docker/secondcloud/mysql/data:/var/lib/mysql
    ports:
      - 3306:3306
